// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// 기본 Firebase 옵션 설정
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2U56xPgPIt4yWeu4TY5kuZT55wXSV9WY',
    appId: '1:471717023137:web:2fe8c2c0f23b3d7b944fe0',
    messagingSenderId: '471717023137',
    projectId: 'coinalarm-55400',
    authDomain: 'coinalarm-55400.firebaseapp.com',
    databaseURL: 'https://coinalarm-55400-default-rtdb.firebaseio.com',
    storageBucket: 'coinalarm-55400.firebasestorage.app',
    measurementId: 'G-W2TP22XT0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdVtFTxfuXI_2tNDd3FSfFg8fwxtDzaQo',
    appId: '1:471717023137:android:3fd397650a992a93944fe0',
    messagingSenderId: '471717023137',
    projectId: 'coinalarm-55400',
    databaseURL: 'https://coinalarm-55400-default-rtdb.firebaseio.com',
    storageBucket: 'coinalarm-55400.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJmH5wPU_zNsmkkn3q7qyfbEunHBQc_G0',
    appId: '1:471717023137:ios:6a9a0be1a7a8a27f944fe0',
    messagingSenderId: '471717023137',
    projectId: 'coinalarm-55400',
    databaseURL: 'https://coinalarm-55400-default-rtdb.firebaseio.com',
    storageBucket: 'coinalarm-55400.firebasestorage.app',
    iosBundleId: 'com.example.coinAlarm',
    androidClientId:
        '471717023137-3fd397650a992a93944fe0.apps.googleusercontent.com',
    iosClientId:
        '471717023137-6a9a0be1a7a8a27f944fe0.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJmH5wPU_zNsmkkn3q7qyfbEunHBQc_G0',
    appId: '1:471717023137:ios:6a9a0be1a7a8a27f944fe0',
    messagingSenderId: '471717023137',
    projectId: 'coinalarm-55400',
    databaseURL: 'https://coinalarm-55400-default-rtdb.firebaseio.com',
    storageBucket: 'coinalarm-55400.firebasestorage.app',
    iosBundleId: 'com.example.coinAlarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2U56xPgPIt4yWeu4TY5kuZT55wXSV9WY',
    appId: '1:471717023137:web:88a6b82ca3a44389944fe0',
    messagingSenderId: '471717023137',
    projectId: 'coinalarm-55400',
    authDomain: 'coinalarm-55400.firebaseapp.com',
    databaseURL: 'https://coinalarm-55400-default-rtdb.firebaseio.com',
    storageBucket: 'coinalarm-55400.firebasestorage.app',
    measurementId: 'G-5B64Z0RL2Y',
  );
}
