// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// 기본 Firebase 옵션 설정
///
/// 실제 값은 Firebase 콘솔에서 앱을 등록한 후 생성된 값으로 대체해야 합니다.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 웹 플랫폼 설정 (테스트용 값)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgUhHU8wSJgO5MVNy95tMT07NEjzMOfz0',
    appId: '1:448618578101:web:0b650370bb29e29cac3efc',
    messagingSenderId: '448618578101',
    projectId: 'react-native-firebase-testing',
    authDomain: 'react-native-firebase-testing.firebaseapp.com',
    storageBucket: 'react-native-firebase-testing.appspot.com',
    measurementId: 'G-F79DJ0VFGS',
  );

  // 안드로이드 플랫폼 설정 (테스트용 값)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuu4tbv9CwwTudNOweMNstzZHIDBhgJxA',
    appId: '1:448618578101:android:0446912d5f1476b6ac3efc',
    messagingSenderId: '448618578101',
    projectId: 'react-native-firebase-testing',
    storageBucket: 'react-native-firebase-testing.appspot.com',
  );

  // iOS 플랫폼 설정 (테스트용 값)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHAsf51D0A407EklG1bs-5wA7EbyfNFg0',
    appId: '1:448618578101:ios:0b259f8a0d57ccecac3efc',
    messagingSenderId: '448618578101',
    projectId: 'react-native-firebase-testing',
    storageBucket: 'react-native-firebase-testing.appspot.com',
    iosClientId:
        '448618578101-28tsenal97j4v1nljt65h7r2tgnp0q11.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.plugins.firebaseCoreTesting',
  );

  // macOS 플랫폼 설정 (테스트용 값)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHAsf51D0A407EklG1bs-5wA7EbyfNFg0',
    appId: '1:448618578101:ios:0b259f8a0d57ccecac3efc',
    messagingSenderId: '448618578101',
    projectId: 'react-native-firebase-testing',
    storageBucket: 'react-native-firebase-testing.appspot.com',
    iosClientId:
        '448618578101-28tsenal97j4v1nljt65h7r2tgnp0q11.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.plugins.firebaseCoreTesting',
  );
}
