[supervisord]
nodaemon=true

[program:news-crawler]
command=python /app/news-crawler/crawler.py
autostart=true
autorestart=true
stdout_logfile=/app/logs/news-crawler.log
stderr_logfile=/app/logs/news-crawler.err.log

[program:news-cleaner]
command=python /app/news-cleaner/cleaner.py
autostart=true
autorestart=true
stdout_logfile=/app/logs/news-cleaner.log
stderr_logfile=/app/logs/news-cleaner.err.log

[program:news-writer]
command=python /app/news-writer/writer.py
autostart=true
autorestart=true
stdout_logfile=/app/logs/news-writer.log
stderr_logfile=/app/logs/news-writer.err.log

[program:logger]
command=python /app/logger/app.py
autostart=true
autorestart=true
stdout_logfile=/app/logs/logger.log
stderr_logfile=/app/logs/logger.err.log

[program:scheduler]
command=python /app/scheduler/main.py
autostart=true
autorestart=true
stdout_logfile=/app/logs/scheduler.log
stderr_logfile=/app/logs/scheduler.err.log 